spring:
  security:
    user:
      name: user
      password: teste
      roles: ADMIN, USER
    oauth2:
      client:
        registration:
          google:
            client-id: 1090689393708-mbmtf324es75n9mh9rmoi8ggtu0j2fli.apps.googleusercontent.com
            client-secret: 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