-- Cria TB_CONFIGURACAO_USUARIO e LOCALIZACAO (mapeamentos @Entity)
CREATE TABLE TB_CONFIGURACAO_USUARIO (
  ID_CONFIGURACAO_USUARIO VARCHAR2(36) DEFAULT NULL PRIMARY KEY,
  ALERTA_MOTO_ENTRAR_PATIO         NUMBER(1) CHECK (ALERTA_MOTO_ENTRAR_PATIO IN (0,1)),
  ALERTA_MOTO_SAIR_PATIO           NUMBER(1) CHECK (ALERTA_MOTO_SAIR_PATIO IN (0,1)),
  ALERTA_MOTO_CHEGAR_SEM_PLACA     NUMBER(1) CHECK (ALERTA_MOTO_CHEGAR_SEM_PLACA IN (0,1)),
  ALERTA_MOTO_PRECISA_MANUTENCAO    NUMBER(1) CHECK (ALERTA_MOTO_PRECISA_MANUTENCAO IN (0,1)),
  ALERTA_MOTO_PREPARADA_ALUGADA     NUMBER(1) CHECK (ALERTA_MOTO_PREPARADA_ALUGADA IN (0,1))
);

-- A entidade Localizacao não define @Table(name), então uso LOCALIZACAO (Oracle faz uppercase)
CREATE TABLE LOCALIZACAO (
  ID_LOCALIZACAO        VARCHAR2(36) PRIMARY KEY,
  CEP_LOCALIZACAO       VARCHAR2(20),
  LOGRADOURO_LOCALIZACAO VARCHAR2(255),
  BAIRRO_LOCALIZACAO    VARCHAR2(120),
  ESTADO_LOCALIZACAO    VARCHAR2(2),
  REGIAO_LOCALIZACAO    VARCHAR2(50)
);
