CREATE TABLE TB_FILIAL (
  ID_FILIAL      VARCHAR2(36) PRIMARY KEY,
  NOME_FILIAL    VARCHAR2(120) NOT NULL,
  ID_LOCALIZACAO VARCHAR2(36),
  CONSTRAINT UK_FILIAL_LOCALIZACAO UNIQUE (ID_LOCALIZACAO),
  CONSTRAINT FK_FILIAL_LOCALIZACAO FOREIGN KEY (ID_LOCALIZACAO)
    REFERENCES LOCALIZACAO(ID_LOCALIZACAO)
);

CREATE TABLE TB_USUARIO (
  ID_USUARIO               VARCHAR2(36) PRIMARY KEY,
  NOME_USUARIO             VARCHAR2(120),
  CPF_USUARIO              VARCHAR2(14),
  TELEFONE_USUARIO         VARCHAR2(30),
  EMAIL_USUARIO            VARCHAR2(150),
  SENHA_USUARIO            VARCHAR2(255),
  LINK_FOTO_USUARIO        VARCHAR2(500),
  DATA_NASCIMENTO_USUARIO  DATE,
  DATA_CRIACAO_USUARIO     TIMESTAMP,
  ID_CONFIGURACAO_USUARIO  VARCHAR2(36),
  CONSTRAINT UK_USUARIO_CONFIG UNIQUE (ID_CONFIGURACAO_USUARIO),
  CONSTRAINT FK_USUARIO_CONFIG FOREIGN KEY (ID_CONFIGURACAO_USUARIO)
    REFERENCES TB_CONFIGURACAO_USUARIO(ID_CONFIGURACAO_USUARIO)
);

CREATE TABLE TB_USUARIO_FILIAL (
  ID_USUARIO VARCHAR2(36) NOT NULL,
  ID_FILIAL  VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_USUARIO_FILIAL PRIMARY KEY (ID_USUARIO, ID_FILIAL),
  CONSTRAINT FK_UF_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
  CONSTRAINT FK_UF_FILIAL  FOREIGN KEY (ID_FILIAL)  REFERENCES TB_FILIAL(ID_FILIAL)
);
