ALTER TABLE TB_USUARIO ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL_USUARIO);
ALTER TABLE TB_USUARIO ADD CONSTRAINT UK_USUARIO_CPF   UNIQUE (CPF_USUARIO);

CREATE INDEX IDX_FILIAL_NOME  ON TB_FILIAL (NOME_FILIAL);
CREATE INDEX IDX_USUARIO_NOME ON TB_USUARIO (NOME_USUARIO);
